[universal]
	fade_in = "100"
	fade_out = "100"
	delay = "200"

#|========|
#| Events |
#|========|

# -= Boss =- #

# -= Raid =- #

#|============|
#| Structures |
#|============|

# -= Bastion =- #

# -= Crypt =- #

[[crypt1]]
	[[crypt1.trigger]]
		name = "structure"
		identifier = "crypt"
		priority = "70"
		resource_name = "graveyard:crypt"

# -= Desert Temple =- #

# -= Dungeon =- #

# -= End City =- #

# -= Jungle Temple =- #

# -= Mineshaft =- #

# -= Nether Fortress =- #

# -= Ocean Monument =- #

# -= Stronghold =- #

# -= Village =- #

#|==============|
#| Environments |
#|==============|

# -= Underwater =- #

#|=========|
#| Weather |
#|=========|

# -= Storm =- #

# -= Snow =- #

[[snow1]]
	[[snow1.trigger]]
		name = "snowing"
		priority = "52"

[[storm1]]
	[[storm1.trigger]]
		name = "storming"
		priority = "51"

# -= Rain =- #

[[rain1]]
	[[rain1.trigger]]
		name = "raining"
		priority = "50"

#|============|
#| Dimensions |
#|============|

# -= Nether =- #

[[nether1]]
	[[nether1.trigger]]
		name = "dimension"
		identifier = "nether"
		priority = "40"
		resource_name = "nether"

# -= End =- #

[[end1]]
	[[end1.trigger]]
		name = "dimension"
		identifier = "end"
		priority = "40"
		resource_name = "end"

#|=============|
#| Underground |
#|=============|

# -= Caves =- #

[[cave1]]
	[[cave1.trigger]]
		name = "height"
		identifier = "cave"
		priority = "20"
		level = "55"
[[cave2]]
	[[cave2.trigger]]
		name = "height"
		identifier = "cave"
		priority = "20"
		level = "55"
[[cave3]]
	[[cave3.trigger]]
		name = "height"
		identifier = "cave"
		priority = "20"
		level = "55"
[[cave4]]
	[[cave4.trigger]]
		name = "height"
		identifier = "cave"
		priority = "20"
		level = "55"

#|=================|
#| Biome Overrides |
#|=================|

# -= Underground Jungle =- #

# This one in particular is higher priority to override underground triggers defined above
[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "30"
		resource_name = "minecraft:lush_caves"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "30"
		resource_name = "minecraft:lush_caves"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "30"
		resource_name = "minecraft:lush_caves"

# -= Magicky Biomes =- #

[[mushroom1]]
	[[mushroom1.trigger]]
		name = "biome"
		identifier = "magicky"
		priority = "15"
		resource_name = "terralith:warped_mesa|terralith:mirage_isles"

# -= Snowy Badlands =- #

[[icy1]]
	[[icy1.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy2]]
	[[icy2.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy3]]
	[[icy3.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy4]]
	[[icy4.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy5]]
	[[icy5.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "15"
		resource_name = "terralith:snowy_badlands"

#|========|
#| Biomes |
#|========|

# -= Desert =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"

# -= Mesa =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "mesa"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "mesa"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "mesa"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "mesa"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "mesa"

# -= Savanna =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "savanna"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "savanna"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "savanna"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "savanna"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "savanna"

# -= Forest =- #

[[forest1]]
	[[forest1.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest2]]
	[[forest2.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest3]]
	[[forest3.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest4]]
	[[forest4.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"

# -= Icy =- #

[[icy1]]
	[[icy1.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy2]]
	[[icy2.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy3]]
	[[icy3.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy4]]
	[[icy4.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy5]]
	[[icy5.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"

# -= Jungle =- #

[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"

# -= Swamp =- #

[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "swamp"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "swamp"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "swamp"

# -= Mountains =- #

[[mountains1]]
	[[mountains1.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"
[[mountains2]]
	[[mountains2.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"
[[mountains3]]
	[[mountains3.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"

# -= Extreme Hills =- #

[[mountains1]]
	[[mountains1.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "extreme_hills"
[[mountains2]]
	[[mountains2.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "extreme_hills"
[[mountains3]]
	[[mountains3.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "extreme_hills"

# -= Mushroom =- #

[[mushroom1]]
	[[mushroom1.trigger]]
		name = "biome"
		identifier = "magicky"
		priority = "10"
		biome_category = "mushroom"

# -= Ocean =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"

# -= River =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "river"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "river"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "river"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "river"

# -= Beach =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "beach"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "beach"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "beach"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "beach"

# -= Plains =- #

[[plains1]]
	[[plains1.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains2]]
	[[plains2.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains3]]
	[[plains3.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains4]]
	[[plains4.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains5]]
	[[plains5.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"

# -= Taiga =- #

[[taiga1]]
	[[taiga1.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"
[[taiga2]]
	[[taiga2.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"
[[taiga3]]
	[[taiga3.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"