[universal]
	fade_in = "100"
	fade_out = "100"
	delay = "200"

[menu1]
	[menu1.trigger]
		name = "menu"

#|========|
#| Events |
#|========|

# -= Raid =- #

[[raid1]]
	[[raid1.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"
[[raid2]]
	[[raid2.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"
[[raid3]]
	[[raid3.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"
[[raid4]]
	[[raid4.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"
[[raid5]]
	[[raid5.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"
[[raid6]]
	[[raid6.trigger]]
		name = "raid"
		priority = "61"
		identifier = "raid"

# -= Boss =- #

[[boss1]]
	[[boss1.trigger]]
		name = "mob"
		identifier = "boss"
		priority = "60"
		resource_name = "BOSS"
[[boss2]]
	[[boss2.trigger]]
		name = "mob"
		identifier = "boss"
		priority = "60"
		resource_name = "BOSS"

#|============|
#| Structures |
#|============|

# Note that Additional Structures does things the lazy way and doesn't define its own structure types.
# As such it's basically impossible to assign custom tracks to them, and it means that getting songs
# meant for other structures NOT to play in them can also be funky, hence the villager mob check for
# villages, and the dimension check for bastions.

# -= Bastion =- #

[[bastion1]]
	[[bastion1.trigger]]
		name = "structure"
		identifier = "bastion"
		priority = "50"
		resource_name = "minecraft:bastion_remnant"
	[[bastion1.trigger]]
		name = "dimension"
		identifier = "bastion_nether"
		priority = "50"
		resource_name = "nether"

# -= Crypt =- #

[[crypt1]]
	[[crypt1.trigger]]
		name = "structure"
		identifier = "crypt"
		priority = "50"
		resource_name = "graveyard:crypt"

# -= Desert Temple =- #

[[desert_temple1]]
	[[desert_temple1.trigger]]
		name = "structure"
		identifier = "desert_temple"
		priority = "50"
		resource_name = "betterdeserttemples:desert_temple"

# -= Dungeon =- #

[[dungeon1]]
	[[dungeon1.trigger]]
		name = "structure"
		identifier = "skeleton_dungeon"
		priority = "50"
		resource_name = "betterdungeons:skeleton_dungeon"
[[dungeon2]]
	[[dungeon2.trigger]]
		name = "structure"
		identifier = "skeleton_dungeon"
		priority = "50"
		resource_name = "betterdungeons:skeleton_dungeon"
[[dungeon3]]
	[[dungeon3.trigger]]
		name = "structure"
		identifier = "skeleton_dungeon"
		priority = "50"
		resource_name = "betterdungeons:skeleton_dungeon"
[[dungeon4]]
	[[dungeon4.trigger]]
		name = "structure"
		identifier = "skeleton_dungeon"
		priority = "50"
		resource_name = "betterdungeons:skeleton_dungeon"
[[dungeon5]]
	[[dungeon5.trigger]]
		name = "structure"
		identifier = "skeleton_dungeon"
		priority = "50"
		resource_name = "betterdungeons:skeleton_dungeon"

[[dungeon1]]
	[[dungeon1.trigger]]
		name = "structure"
		identifier = "spider_dungeon"
		priority = "50"
		resource_name = "betterdungeons:spider_dungeon"
[[dungeon2]]
	[[dungeon2.trigger]]
		name = "structure"
		identifier = "spider_dungeon"
		priority = "50"
		resource_name = "betterdungeons:spider_dungeon"
[[dungeon3]]
	[[dungeon3.trigger]]
		name = "structure"
		identifier = "spider_dungeon"
		priority = "50"
		resource_name = "betterdungeons:spider_dungeon"
[[dungeon4]]
	[[dungeon4.trigger]]
		name = "structure"
		identifier = "spider_dungeon"
		priority = "50"
		resource_name = "betterdungeons:spider_dungeon"
[[dungeon5]]
	[[dungeon5.trigger]]
		name = "structure"
		identifier = "spider_dungeon"
		priority = "50"
		resource_name = "betterdungeons:spider_dungeon"

[[dungeon1]]
	[[dungeon1.trigger]]
		name = "structure"
		identifier = "zombie_dungeon"
		priority = "50"
		resource_name = "betterdungeons:zombie_dungeon"
[[dungeon2]]
	[[dungeon2.trigger]]
		name = "structure"
		identifier = "zombie_dungeon"
		priority = "50"
		resource_name = "betterdungeons:zombie_dungeon"
[[dungeon3]]
	[[dungeon3.trigger]]
		name = "structure"
		identifier = "zombie_dungeon"
		priority = "50"
		resource_name = "betterdungeons:zombie_dungeon"
[[dungeon4]]
	[[dungeon4.trigger]]
		name = "structure"
		identifier = "zombie_dungeon"
		priority = "50"
		resource_name = "betterdungeons:zombie_dungeon"
[[dungeon5]]
	[[dungeon5.trigger]]
		name = "structure"
		identifier = "zombie_dungeon"
		priority = "50"
		resource_name = "betterdungeons:zombie_dungeon"

[[dungeon1]]
	[[dungeon1.trigger]]
		name = "structure"
		identifier = "mega_dungeon"
		priority = "50"
		resource_name = "quark:mega_dungeon"
[[dungeon2]]
	[[dungeon2.trigger]]
		name = "structure"
		identifier = "mega_dungeon"
		priority = "50"
		resource_name = "quark:mega_dungeon"
[[dungeon3]]
	[[dungeon3.trigger]]
		name = "structure"
		identifier = "mega_dungeon"
		priority = "50"
		resource_name = "quark:mega_dungeon"
[[dungeon4]]
	[[dungeon4.trigger]]
		name = "structure"
		identifier = "mega_dungeon"
		priority = "50"
		resource_name = "quark:mega_dungeon"
[[dungeon5]]
	[[dungeon5.trigger]]
		name = "structure"
		identifier = "mega_dungeon"
		priority = "50"
		resource_name = "quark:mega_dungeon"

# -= End City =- #

[[end_city1]]
	[[end_city1.trigger]]
		name = "structure"
		identifier = "end_city"
		priority = "50"
		resource_name = "minecraft:endcity"

# -= Jungle Temple =- #

[[jungle_temple1]]
	[[jungle_temple1.trigger]]
		name = "structure"
		identifier = "jungle_temple"
		priority = "50"
		resource_name = "minecraft:jungle_pyramid"

# -= Mansion =- #

[[mansion1]]
	[[mansion1.trigger]]
		name = "structure"
		identifier = "mansion"
		priority = "50"
		resource_name = "biomemakeover:mansion"

# -= Mineshaft =- #

# -= Nether Fortress =- #

[[nether_fortress1]]
	[[nether_fortress1.trigger]]
		name = "structure"
		identifier = "fortress"
		priority = "50"
		resource_name = "minecraft:fortress"

# -= Ocean Monument =- #

[[ocean_monument1]]
	[[ocean_monument1.trigger]]
		name = "structure"
		identifier = "monument"
		priority = "50"
		resource_name = "minecraft:monument"

# -= Pillager Outpost =- #

[[mansion1]]
	[[mansion1.trigger]]
		name = "structure"
		identifier = "pillager_outpost"
		priority = "50"
		resource_name = "minecraft:pillager_outpost"

# -= Stronghold =- #

[[stronghold1]]
	[[stronghold1.trigger]]
		name = "structure"
		identifier = "stronghold"
		priority = "50"
		resource_name = "minecraft:stronghold"

# -= Village =- #

[[village1]]
	[[village1.trigger]]
		name = "structure"
		identifier = "village"
		priority = "50"
		resource_name = "minecraft:village"
	[[village1.trigger]]
		name = "mob"
		identifier = "villager"
		priority = "50"
		resource_name = "minecraft:villager"
		level = "1"
		detection_range = "64"
[[village2]]
	[[village2.trigger]]
		name = "structure"
		identifier = "village"
		priority = "50"
		resource_name = "minecraft:village"
	[[village2.trigger]]
		name = "mob"
		identifier = "villager"
		priority = "50"
		resource_name = "minecraft:villager"
		level = "1"
		detection_range = "64"
[[village3]]
	[[village3.trigger]]
		name = "structure"
		identifier = "village"
		priority = "50"
		resource_name = "minecraft:village"
	[[village3.trigger]]
		name = "mob"
		identifier = "villager"
		priority = "50"
		resource_name = "minecraft:villager"
		level = "1"
		detection_range = "64"

#|==============|
#| Environments |
#|==============|

# -= Underwater =- #

[[underwater1]]
	[[underwater1.trigger]]
		name = "underwater"
		priority = "45"
		start = "100"

#|============|
#| Dimensions |
#|============|

# -= Nether =- #

[[nether1]]
	[[nether1.trigger]]
		name = "dimension"
		identifier = "nether"
		priority = "40"
		resource_name = "nether"
[[nether2]]
	[[nether2.trigger]]
		name = "dimension"
		identifier = "nether"
		priority = "40"
		resource_name = "nether"
[[nether3]]
	[[nether3.trigger]]
		name = "dimension"
		identifier = "nether"
		priority = "40"
		resource_name = "nether"

# -= End =- #

[[end1]]
	[[end1.trigger]]
		name = "dimension"
		identifier = "end"
		priority = "40"
		resource_name = "end"
[[end2]]
	[[end2.trigger]]
		name = "dimension"
		identifier = "end"
		priority = "40"
		resource_name = "end"
[[end3]]
	[[end3.trigger]]
		name = "dimension"
		identifier = "end"
		priority = "40"
		resource_name = "end"
[[end4]]
	[[end4.trigger]]
		name = "dimension"
		identifier = "end"
		priority = "40"
		resource_name = "end"

#|=============|
#| Underground |
#|=============|

# -= Caves =- #

[[cave1]]
	[[cave1.trigger]]
		name = "height"
		identifier = "cave"
		priority = "25"
		level = "55"
[[cave2]]
	[[cave2.trigger]]
		name = "height"
		identifier = "cave"
		priority = "25"
		level = "55"
[[cave3]]
	[[cave3.trigger]]
		name = "height"
		identifier = "cave"
		priority = "25"
		level = "55"
[[cave4]]
	[[cave4.trigger]]
		name = "height"
		identifier = "cave"
		priority = "25"
		level = "55"

#|=========|
#| Weather |
#|=========|

# -= Snow =- #

[[snow1]]
	[[snow1.trigger]]
		name = "snowing"
		priority = "22"

# -= Storm =- #

[[storm1]]
	[[storm1.trigger]]
		name = "storming"
		priority = "21"

# -= Rain =- #

[[rain1]]
	[[rain1.trigger]]
		name = "raining"
		priority = "20"

#|=================|
#| Biome Overrides |
#|=================|

# -= Underground Jungle =- #

# This one in particular is higher priority to override underground triggers defined above
[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "lush_caves"
		priority = "30"
		resource_name = "minecraft:lush_caves"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "lush_caves"
		priority = "30"
		resource_name = "minecraft:lush_caves"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "lush_caves"
		priority = "30"
		resource_name = "minecraft:lush_caves"

# -= Magicky Biomes =- #

[[mushroom1]]
	[[mushroom1.trigger]]
		name = "biome"
		identifier = "warped_mesa"
		priority = "15"
		resource_name = "terralith:warped_mesa"

[[mushroom1]]
	[[mushroom1.trigger]]
		name = "biome"
		identifier = "mirage_isles"
		priority = "15"
		resource_name = "terralith:mirage_isles"

# -= Snowy Badlands =- #

[[icy1]]
	[[icy1.trigger]]
		name = "biome"
		identifier = "snowy_badlands"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy2]]
	[[icy2.trigger]]
		name = "biome"
		identifier = "snowy_badlands"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy3]]
	[[icy3.trigger]]
		name = "biome"
		identifier = "snowy_badlands"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy4]]
	[[icy4.trigger]]
		name = "biome"
		identifier = "snowy_badlands"
		priority = "15"
		resource_name = "terralith:snowy_badlands"
[[icy5]]
	[[icy5.trigger]]
		name = "biome"
		identifier = "snowy_badlands"
		priority = "15"
		resource_name = "terralith:snowy_badlands"

#|========|
#| Biomes |
#|========|

# -= Desert =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "desert"
		priority = "10"
		biome_category = "desert"

# -= Mesa =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "mesa"
		priority = "10"
		biome_category = "mesa"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "mesa"
		priority = "10"
		biome_category = "mesa"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "mesa"
		priority = "10"
		biome_category = "mesa"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "mesa"
		priority = "10"
		biome_category = "mesa"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "mesa"
		priority = "10"
		biome_category = "mesa"

# -= Savanna =- #

[[desert1]]
	[[desert1.trigger]]
		name = "biome"
		identifier = "savanna"
		priority = "10"
		biome_category = "savanna"
[[desert2]]
	[[desert2.trigger]]
		name = "biome"
		identifier = "savanna"
		priority = "10"
		biome_category = "savanna"
[[desert3]]
	[[desert3.trigger]]
		name = "biome"
		identifier = "savanna"
		priority = "10"
		biome_category = "savanna"
[[desert4]]
	[[desert4.trigger]]
		name = "biome"
		identifier = "savanna"
		priority = "10"
		biome_category = "savanna"
[[desert5]]
	[[desert5.trigger]]
		name = "biome"
		identifier = "savanna"
		priority = "10"
		biome_category = "savanna"

# -= Forest =- #

[[forest1]]
	[[forest1.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest2]]
	[[forest2.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest3]]
	[[forest3.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"
[[forest4]]
	[[forest4.trigger]]
		name = "biome"
		identifier = "forest"
		priority = "10"
		biome_category = "forest"

# -= Icy =- #

[[icy1]]
	[[icy1.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy2]]
	[[icy2.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy3]]
	[[icy3.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy4]]
	[[icy4.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"
[[icy5]]
	[[icy5.trigger]]
		name = "biome"
		identifier = "icy"
		priority = "10"
		biome_category = "icy"

# -= Jungle =- #

[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "jungle"
		priority = "10"
		biome_category = "jungle"

# -= Swamp =- #

[[jungle1]]
	[[jungle1.trigger]]
		name = "biome"
		identifier = "swamp"
		priority = "10"
		biome_category = "swamp"
[[jungle2]]
	[[jungle2.trigger]]
		name = "biome"
		identifier = "swamp"
		priority = "10"
		biome_category = "swamp"
[[jungle3]]
	[[jungle3.trigger]]
		name = "biome"
		identifier = "swamp"
		priority = "10"
		biome_category = "swamp"

# -= Mountains =- #

[[mountains1]]
	[[mountains1.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"
[[mountains2]]
	[[mountains2.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"
[[mountains3]]
	[[mountains3.trigger]]
		name = "biome"
		identifier = "mountain"
		priority = "10"
		biome_category = "mountain"

# -= Extreme Hills =- #

[[mountains1]]
	[[mountains1.trigger]]
		name = "biome"
		identifier = "extreme_hills"
		priority = "10"
		biome_category = "extreme_hills"
[[mountains2]]
	[[mountains2.trigger]]
		name = "biome"
		identifier = "extreme_hills"
		priority = "10"
		biome_category = "extreme_hills"
[[mountains3]]
	[[mountains3.trigger]]
		name = "biome"
		identifier = "extreme_hills"
		priority = "10"
		biome_category = "extreme_hills"

# -= Mushroom =- #

[[mushroom1]]
	[[mushroom1.trigger]]
		name = "biome"
		identifier = "mushroom"
		priority = "10"
		biome_category = "mushroom"

# -= Ocean =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "ocean"
		priority = "10"
		biome_category = "ocean"

# -= River =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "river"
		priority = "10"
		biome_category = "river"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "river"
		priority = "10"
		biome_category = "river"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "river"
		priority = "10"
		biome_category = "river"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "river"
		priority = "10"
		biome_category = "river"

# -= Beach =- #

[[ocean1]]
	[[ocean1.trigger]]
		name = "biome"
		identifier = "beach"
		priority = "10"
		biome_category = "beach"
[[ocean2]]
	[[ocean2.trigger]]
		name = "biome"
		identifier = "beach"
		priority = "10"
		biome_category = "beach"
[[ocean3]]
	[[ocean3.trigger]]
		name = "biome"
		identifier = "beach"
		priority = "10"
		biome_category = "beach"
[[ocean4]]
	[[ocean4.trigger]]
		name = "biome"
		identifier = "beach"
		priority = "10"
		biome_category = "beach"

# -= Plains =- #

[[plains1]]
	[[plains1.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains2]]
	[[plains2.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains3]]
	[[plains3.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains4]]
	[[plains4.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"
[[plains5]]
	[[plains5.trigger]]
		name = "biome"
		identifier = "plains"
		priority = "10"
		biome_category = "plains"

# -= Taiga =- #

[[taiga1]]
	[[taiga1.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"
[[taiga2]]
	[[taiga2.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"
[[taiga3]]
	[[taiga3.trigger]]
		name = "biome"
		identifier = "taiga"
		priority = "10"
		biome_category = "taiga"