[universal]
	fade_in = "100"
	fade_out = "100"
	delay = "200"

[main_menu]
	[main_menu.trigger]
		name = "menu"

[raid]
	[raid.trigger]
		priority = "11"
		name = "raid"
		identifier = "raid"

[night_home]
	[[night_home.trigger]]
		priority = "10"
		name = "home"
		detection_range = "64"
	[[night_home.trigger]]
		priority = "10"
		name = "time"
		start = "night"
		identifier = "night10"
	[[night_home.trigger]]
		priority = "10"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld10"

[home]
	[[home.trigger]]
		priority = "9"
		name = "home"
		detection_range = "64"
	[[home.trigger]]
		priority = "9"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld9"

[bastion]
	[bastion.trigger]
		priority = "8"
		name = "structure"
		resource_name = "minecraft:bastion_remnant"
		identifier = "str_bastion"

[mineshaft]
	[mineshaft.trigger]
		priority = "8"
		name = "structure"
		resource_name = "bettermineshafts:mineshaft"
		identifier = "str_mineshaft"

[stronghold]
	[stronghold.trigger]
		priority = "8"
		name = "structure"
		resource_name = "betterstrongholds:stronghold"
		identifier = "str_stronghold"

[underground_biome]
	[[underground_biome.trigger]]
		priority = "7"
		name = "biome"
		biome_category = "underground"
		identifier = "biome_underground"
	[[underground_biome.trigger]]
		priority = "7"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld7"

[deep_underground]
	[[deep_underground.trigger]]
		priority = "6"
		name = "height"
		level = "-5"
		identifier = "height_minus5"
	[[deep_underground.trigger]]
		priority = "6"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld6"

[underground]
	[[underground.trigger]]
		priority = "5"
		name = "height"
		level = "55"
		identifier = "height_55"
	[[underground.trigger]]
		priority = "5"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld5"

[rain]
	[[rain.trigger]]
		priority = "4"
		name = "raining"
	[[rain.trigger]]
		priority = "4"
		name = "biome"
		rain_type = "rain"
		identifier = "biome_rain4"

[storm]
	[[storm.trigger]]
		priority = "4"
		name = "storming"
	[[storm.trigger]]
		name = "biome"
		identifier = "biome_rain4"

[snowing]
	[[snowing.trigger]]
		priority = "4"
		name = "snowing"
	[[snowing.trigger]]
		priority = "4"
		name = "biome"
		rain_type = "snow"
		identifier = "biome_snow4"

[night_desert]
	[[night_desert.trigger]]
		priority = "3"
		name = "biome"
		biome_category = "desert"
		identifier = "biome_desert3"
	[[night_desert.trigger]]
		priority = "3"
		name = "time"
		start = "night"
		end = "day"
		identifier = "night3"

[night_forest]
	[[night_forest.trigger]]
		priority = "3"
		name = "biome"
		biome_category = "forest"
		identifier = "biome_forest3"
	[[night_forest.trigger]]
		name = "time"
		identifier = "night3"

[night_snowy]
	[[night_snowy.trigger]]
		priority = "3"
		name = "biome"
		biome_category = "icy"
		identifier = "biome_icy3"
	[[night_snowy.trigger]]
		name = "time"
		identifier = "night3"

[night]
	[[night.trigger]]
		priority = "2"
		name = "time"
		start = "night"
		identifier = "night2"
	[[night.trigger]]
		priority = "2"
		name = "dimension"
		resource_name = "overworld"
		identifier = "overworld2"

[desert_village]
	[[desert_village.trigger]]
		priority = "1"
		name = "structure"
		resource_name = "minecraft:village"
		identifier = "str_desert_village"
	[[desert_village.trigger]]
		priority = "1"
		name = "biome"
		biome_category = "desert"
		identifier = "biome_desert1"

[plains_village]
	[[plains_village.trigger]]
		priority = "1"
		name = "structure"
		resource_name = "minecraft:village"
		identifier = "str_plains_village"
	[[plains_village.trigger]]
		priority = "1"
		name = "biome"
		biome_category = "plains"
		identifier = "biome_plains1"

[savanna_village]
	[[savanna_village.trigger]]
		priority = "1"
		name = "structure"
		resource_name = "minecraft:village"
		identifier = "str_savanna_village"
	[[savanna_village.trigger]]
		priority = "1"
		name = "biome"
		biome_category = "savanna"
		identifier = "biome_savanna1"

[snowy_village]
	[[snowy_village.trigger]]
		priority = "1"
		name = "structure"
		resource_name = "minecraft:village"
		identifier = "str_snowy_village"
	[[snowy_village.trigger]]
		priority = "1"
		name = "biome"
		biome_category = "icy"
		identifier = "biome_icy1"

[taiga_village]
	[[taiga_village.trigger]]
		priority = "1"
		name = "structure"
		resource_name = "minecraft:village"
		identifier = "str_taiga_village"
	[[taiga_village.trigger]]
		priority = "1"
		name = "biome"
		biome_category = "taiga"
		identifier = "biome_taiga1"

[beach]
	[beach.trigger]
		priority = "0"
		name = "biome"
		biome_category = "beach"
		identifier = "biome_beach"

[desert]
	[desert.trigger]
		priority = "0"
		name = "biome"
		biome_category = "desert"
		identifier = "biome_desert"

[end]
	[end.trigger]
		priority = "0"
		name = "biome"
		biome_category = "end"
		identifier = "biome_end"

[forest]
	[forest.trigger]
		priority = "0"
		name = "biome"
		biome_category = "forest"
		identifier = "biome_forest"

[icy]
	[icy.trigger]
		priority = "0"
		name = "biome"
		biome_category = "icy"
		identifier = "biome_icy"

[jungle]
	[jungle.trigger]
		priority = "0"
		name = "biome"
		biome_category = "jungle"
		identifier = "biome_jungle"

[mesa]
	[mesa.trigger]
		priority = "0"
		name = "biome"
		biome_category = "mesa"
		identifier = "biome_mesa"

[mountain]
	[[mountain.trigger]]
		priority = "0"
		name = "biome"
		biome_category = "mountain;extreme_hills"
		identifier = "biome_extreme_hills"

[mushroom]
	[mushroom.trigger]
		priority = "0"
		name = "biome"
		biome_category = "mushroom"
		identifier = "biome_mushroom"

[nether]
	[nether.trigger]
		priority = "0"
		name = "biome"
		biome_category = "nether"
		identifier = "biome_nether"

[ocean]
	[ocean.trigger]
		priority = "0"
		name = "biome"
		biome_category = "ocean"
		identifier = "biome_ocean"

[plains]
	[plains.trigger]
		priority = "0"
		name = "biome"
		biome_category = "plains"
		identifier = "biome_plains"

[river]
	[river.trigger]
		priority = "0"
		name = "biome"
		biome_category = "river"
		identifier = "biome_river"

[savanna]
	[savanna.trigger]
		priority = "0"
		name = "biome"
		biome_category = "savanna"
		identifier = "biome_savanna"

[swamp]
	[swamp.trigger]
		priority = "0"
		name = "biome"
		biome_category = "swamp"
		identifier = "biome_swamp"

[taiga]
	[taiga.trigger]
		priority = "0"
		name = "biome"
		biome_category = "taiga"
		identifier = "biome_taiga"
